#![allow(non_camel_case_types)]

use windows::Win32::Foundation::*;

#[repr(C)]
pub enum PATH_TYPE {
    DOS_PATH,
    _NT_PATH,
}
pub type WORD = u16;
pub type DWORD = u32;
pub type QWORD = u64;
pub type PDB = HANDLE;
pub type TAG = DWORD;
pub type INDEXID = DWORD;
pub type TAGID = DWORD;
pub type PBYTE = *mut u8;
pub enum c_void {}
pub type PVOID = *mut c_void;

// Tags
pub const TAGID_NULL: DWORD = 0x00;

// TAG_TYPE_NULL
pub const TAG_TYPE_NULL: DWORD = 0x1000;
pub const TAG_INCLUDE: DWORD = 0x1 | TAG_TYPE_NULL;
pub const TAG_GENERAL: DWORD = 0x2 | TAG_TYPE_NULL;
pub const TAG_MATCH_LOGIC_NOT: DWORD = 0x3 | TAG_TYPE_NULL;
pub const TAG_APPLY_ALL_SHIMS: DWORD = 0x4 | TAG_TYPE_NULL;
pub const TAG_USE_SERVICE_PACK_FILES: DWORD = 0x5 | TAG_TYPE_NULL;
pub const TAG_MITIGATION_OS: DWORD = 0x6 | TAG_TYPE_NULL;
pub const TAG_BLOCK_UPGRADE: DWORD = 0x7 | TAG_TYPE_NULL;
pub const TAG_INCLUDEEXCLUDEDLL: DWORD = 0x8 | TAG_TYPE_NULL;

// TAG_TYPE_WORD
pub const TAG_TYPE_WORD: DWORD = 0x3000;
pub const TAG_MATCH_MODE: DWORD = 0x1 | TAG_TYPE_WORD;
pub const TAG_TAG: DWORD = 0x801 | TAG_TYPE_WORD;
pub const TAG_INDEX_TAG: DWORD = 0x802 | TAG_TYPE_WORD;
pub const TAG_INDEX_KEY: DWORD = 0x803 | TAG_TYPE_WORD;

// TAG_TYPE_DWORD
pub const TAG_TYPE_DWORD: DWORD = 0x4000;
pub const TAG_SIZE: DWORD = 0x1 | TAG_TYPE_DWORD;
pub const TAG_OFFSET: DWORD = 0x2 | TAG_TYPE_DWORD;
pub const TAG_CHECKSUM: DWORD = 0x3 | TAG_TYPE_DWORD;
pub const TAG_SHIM_TAGID: DWORD = 0x4 | TAG_TYPE_DWORD;
pub const TAG_PATCH_TAGID: DWORD = 0x5 | TAG_TYPE_DWORD;
pub const TAG_MODULE_TYPE: DWORD = 0x6 | TAG_TYPE_DWORD;
pub const TAG_VERDATEHI: DWORD = 0x7 | TAG_TYPE_DWORD;
pub const TAG_VERDATELO: DWORD = 0x8 | TAG_TYPE_DWORD;
pub const TAG_VERFILEOS: DWORD = 0x9 | TAG_TYPE_DWORD;
pub const TAG_VERFILETYPE: DWORD = 0xA | TAG_TYPE_DWORD;
pub const TAG_PE_CHECKSUM: DWORD = 0xB | TAG_TYPE_DWORD;
pub const TAG_PREVOSMAJORVER: DWORD = 0xC | TAG_TYPE_DWORD;
pub const TAG_PREVOSMINORVER: DWORD = 0xD | TAG_TYPE_DWORD;
pub const TAG_PREVOSPLATFORMID: DWORD = 0xE | TAG_TYPE_DWORD;
pub const TAG_PREVOSBUILDNO: DWORD = 0xF | TAG_TYPE_DWORD;
pub const TAG_PROBLEMSEVERITY: DWORD = 0x10 | TAG_TYPE_DWORD;
pub const TAG_LANGID: DWORD = 0x11 | TAG_TYPE_DWORD;
pub const TAG_VER_LANGUAGE: DWORD = 0x12 | TAG_TYPE_DWORD;
pub const TAG_ENGINE: DWORD = 0x14 | TAG_TYPE_DWORD;
pub const TAG_HTMLHELPID: DWORD = 0x15 | TAG_TYPE_DWORD;
pub const TAG_INDEX_FLAGS: DWORD = 0x16 | TAG_TYPE_DWORD;
pub const TAG_FLAGS: DWORD = 0x17 | TAG_TYPE_DWORD;
pub const TAG_DATA_VALUETYPE: DWORD = 0x18 | TAG_TYPE_DWORD;
pub const TAG_DATA_DWORD: DWORD = 0x19 | TAG_TYPE_DWORD;
pub const TAG_LAYER_TAGID: DWORD = 0x1A | TAG_TYPE_DWORD;
pub const TAG_MSI_TRANSFORM_TAGID: DWORD = 0x1B | TAG_TYPE_DWORD;
pub const TAG_LINKER_VERSION: DWORD = 0x1C | TAG_TYPE_DWORD;
pub const TAG_LINK_DATE: DWORD = 0x1D | TAG_TYPE_DWORD;
pub const TAG_UPTO_LINK_DATE: DWORD = 0x1E | TAG_TYPE_DWORD;
pub const TAG_OS_SERVICE_PACK: DWORD = 0x1F | TAG_TYPE_DWORD;
pub const TAG_FLAG_TAGID: DWORD = 0x20 | TAG_TYPE_DWORD;
pub const TAG_RUNTIME_PLATFORM: DWORD = 0x21 | TAG_TYPE_DWORD;
pub const TAG_OS_SKU: DWORD = 0x22 | TAG_TYPE_DWORD;
pub const TAG_OS_PLATFORM: DWORD = 0x23 | TAG_TYPE_DWORD;
pub const TAG_APP_NAME_RC_ID: DWORD = 0x24 | TAG_TYPE_DWORD;
pub const TAG_VENDOR_NAME_RC_ID: DWORD = 0x25 | TAG_TYPE_DWORD;
pub const TAG_SUMMARY_MSG_RC_ID: DWORD = 0x26 | TAG_TYPE_DWORD;
pub const TAG_VISTA_SKU: DWORD = 0x27 | TAG_TYPE_DWORD;
pub const TAG_DESCRIPTION_RC_ID: DWORD = 0x28 | TAG_TYPE_DWORD;
pub const TAG_PARAMETER1_RC_ID: DWORD = 0x29 | TAG_TYPE_DWORD;
pub const TAG_TAGID: DWORD = 0x801 | TAG_TYPE_DWORD;

// TAG_TYPE_QWORD
pub const TAG_TYPE_QWORD: DWORD = 0x5000;
pub const TAG_TIME: DWORD = 0x1 | TAG_TYPE_QWORD;
pub const TAG_BIN_FILE_VERSION: DWORD = 0x2 | TAG_TYPE_QWORD;
pub const TAG_BIN_PRODUCT_VERSION: DWORD = 0x3 | TAG_TYPE_QWORD;
pub const TAG_MODTIME: DWORD = 0x4 | TAG_TYPE_QWORD;
pub const TAG_FLAG_MASK_KERNEL: DWORD = 0x5 | TAG_TYPE_QWORD;
pub const TAG_UPTO_BIN_PRODUCT_VERSION: DWORD = 0x6 | TAG_TYPE_QWORD;
pub const TAG_DATA_QWORD: DWORD = 0x7 | TAG_TYPE_QWORD;
pub const TAG_FLAG_MASK_USER: DWORD = 0x8 | TAG_TYPE_QWORD;
pub const TAG_FLAGS_NTVDM1: DWORD = 0x9 | TAG_TYPE_QWORD;
pub const TAG_FLAGS_NTVDM2: DWORD = 0xA | TAG_TYPE_QWORD;
pub const TAG_FLAGS_NTVDM3: DWORD = 0xB | TAG_TYPE_QWORD;
pub const TAG_FLAG_MASK_SHELL: DWORD = 0xC | TAG_TYPE_QWORD;
pub const TAG_UPTO_BIN_FILE_VERSION: DWORD = 0xD | TAG_TYPE_QWORD;
pub const TAG_FLAG_MASK_FUSION: DWORD = 0xE | TAG_TYPE_QWORD;
pub const TAG_FLAG_PROCESSPARAM: DWORD = 0xF | TAG_TYPE_QWORD;
pub const TAG_FLAG_LUA: DWORD = 0x10 | TAG_TYPE_QWORD;
pub const TAG_FLAG_INSTALL: DWORD = 0x11 | TAG_TYPE_QWORD;

// TAG_TYPE_STRINGREF
pub const TAG_TYPE_STRINGREF: DWORD = 0x6000;
pub const TAG_NAME: DWORD = 0x1 | TAG_TYPE_STRINGREF;
pub const TAG_DESCRIPTION: DWORD = 0x2 | TAG_TYPE_STRINGREF;
pub const TAG_MODULE: DWORD = 0x3 | TAG_TYPE_STRINGREF;
pub const TAG_API: DWORD = 0x4 | TAG_TYPE_STRINGREF;
pub const TAG_VENDOR: DWORD = 0x5 | TAG_TYPE_STRINGREF;
pub const TAG_APP_NAME: DWORD = 0x6 | TAG_TYPE_STRINGREF;
pub const TAG_COMMAND_LINE: DWORD = 0x8 | TAG_TYPE_STRINGREF;
pub const TAG_COMPANY_NAME: DWORD = 0x9 | TAG_TYPE_STRINGREF;
pub const TAG_DLLFILE: DWORD = 0xA | TAG_TYPE_STRINGREF;
pub const TAG_WILDCARD_NAME: DWORD = 0xB | TAG_TYPE_STRINGREF;
pub const TAG_PRODUCT_NAME: DWORD = 0x10 | TAG_TYPE_STRINGREF;
pub const TAG_PRODUCT_VERSION: DWORD = 0x11 | TAG_TYPE_STRINGREF;
pub const TAG_FILE_DESCRIPTION: DWORD = 0x12 | TAG_TYPE_STRINGREF;
pub const TAG_FILE_VERSION: DWORD = 0x13 | TAG_TYPE_STRINGREF;
pub const TAG_ORIGINAL_FILENAME: DWORD = 0x14 | TAG_TYPE_STRINGREF;
pub const TAG_INTERNAL_NAME: DWORD = 0x15 | TAG_TYPE_STRINGREF;
pub const TAG_LEGAL_COPYRIGHT: DWORD = 0x16 | TAG_TYPE_STRINGREF;
pub const TAG_16BIT_DESCRIPTION: DWORD = 0x17 | TAG_TYPE_STRINGREF;
pub const TAG_APPHELP_DETAILS: DWORD = 0x18 | TAG_TYPE_STRINGREF;
pub const TAG_LINK_URL: DWORD = 0x19 | TAG_TYPE_STRINGREF;
pub const TAG_LINK_TEXT: DWORD = 0x1A | TAG_TYPE_STRINGREF;
pub const TAG_APPHELP_TITLE: DWORD = 0x1B | TAG_TYPE_STRINGREF;
pub const TAG_APPHELP_CONTACT: DWORD = 0x1C | TAG_TYPE_STRINGREF;
pub const TAG_SXS_MANIFEST: DWORD = 0x1D | TAG_TYPE_STRINGREF;
pub const TAG_DATA_STRING: DWORD = 0x1E | TAG_TYPE_STRINGREF;
pub const TAG_MSI_TRANSFORM_FILE: DWORD = 0x1F | TAG_TYPE_STRINGREF;
pub const TAG_16BIT_MODULE_NAME: DWORD = 0x20 | TAG_TYPE_STRINGREF;
pub const TAG_LAYER_DISPLAYNAME: DWORD = 0x21 | TAG_TYPE_STRINGREF;
pub const TAG_COMPILER_VERSION: DWORD = 0x22 | TAG_TYPE_STRINGREF;
pub const TAG_ACTION_TYPE: DWORD = 0x23 | TAG_TYPE_STRINGREF;
pub const TAG_EXPORT_NAME: DWORD = 0x24 | TAG_TYPE_STRINGREF;

// TAG_TYPE_LIST
pub const TAG_TYPE_LIST: DWORD = 0x7000;
pub const TAG_DATABASE: DWORD = 0x1 | TAG_TYPE_LIST;
pub const TAG_LIBRARY: DWORD = 0x2 | TAG_TYPE_LIST;
pub const TAG_INEXCLUDE: DWORD = 0x3 | TAG_TYPE_LIST;
pub const TAG_SHIM: DWORD = 0x4 | TAG_TYPE_LIST;
pub const TAG_PATCH: DWORD = 0x5 | TAG_TYPE_LIST;
pub const TAG_APP: DWORD = 0x6 | TAG_TYPE_LIST;
pub const TAG_EXE: DWORD = 0x7 | TAG_TYPE_LIST;
pub const TAG_MATCHING_FILE: DWORD = 0x8 | TAG_TYPE_LIST;
pub const TAG_SHIM_REF: DWORD = 0x9 | TAG_TYPE_LIST;
pub const TAG_PATCH_REF: DWORD = 0xA | TAG_TYPE_LIST;
pub const TAG_LAYER: DWORD = 0xB | TAG_TYPE_LIST;
pub const TAG_FILE: DWORD = 0xC | TAG_TYPE_LIST;
pub const TAG_APPHELP: DWORD = 0xD | TAG_TYPE_LIST;
pub const TAG_LINK: DWORD = 0xE | TAG_TYPE_LIST;
pub const TAG_DATA: DWORD = 0xF | TAG_TYPE_LIST;
pub const TAG_MSI_TRANSFORM: DWORD = 0x10 | TAG_TYPE_LIST;
pub const TAG_MSI_TRANSFORM_REF: DWORD = 0x11 | TAG_TYPE_LIST;
pub const TAG_MSI_PACKAGE: DWORD = 0x12 | TAG_TYPE_LIST;
pub const TAG_FLAG: DWORD = 0x13 | TAG_TYPE_LIST;
pub const TAG_MSI_CUSTOM_ACTION: DWORD = 0x14 | TAG_TYPE_LIST;
pub const TAG_FLAG_REF: DWORD = 0x15 | TAG_TYPE_LIST;
pub const TAG_ACTION: DWORD = 0x16 | TAG_TYPE_LIST;
pub const TAG_LOOKUP: DWORD = 0x17 | TAG_TYPE_LIST;
pub const TAG_STRINGTABLE: DWORD = 0x801 | TAG_TYPE_LIST;
pub const TAG_INDEXES: DWORD = 0x802 | TAG_TYPE_LIST;
pub const TAG_INDEX: DWORD = 0x803 | TAG_TYPE_LIST;

// TAG_TYPE_STRING
pub const TAG_TYPE_STRING: DWORD = 0x8000;
pub const TAG_STRINGTABLE_ITEM: DWORD = 0x801 | TAG_TYPE_STRING;

// TAG_TYPE_BINARY
pub const TAG_TYPE_BINARY: DWORD = 0x9000;
pub const TAG_PATCH_BITS: DWORD = 0x2 | TAG_TYPE_BINARY;
pub const TAG_FILE_BITS: DWORD = 0x3 | TAG_TYPE_BINARY;
pub const TAG_EXE_ID: DWORD = 0x4 | TAG_TYPE_BINARY;
pub const TAG_DATA_BITS: DWORD = 0x5 | TAG_TYPE_BINARY;
pub const TAG_MSI_PACKAGE_ID: DWORD = 0x6 | TAG_TYPE_BINARY;
pub const TAG_DATABASE_ID: DWORD = 0x7 | TAG_TYPE_BINARY;
pub const TAG_FIX_ID: DWORD = 0x10 | TAG_TYPE_BINARY;
pub const TAG_INDEX_BITS: DWORD = 0x801 | TAG_TYPE_BINARY;

pub const OS_PLATFORM_32: DWORD = 0x1;
pub const OS_PLATFORM_64: DWORD = 0x4;
