[package]
name = "shim"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
edition = { workspace = true }

[dependencies]
windows = { workspace = true }
shimlib = { path = "../shimlib" }

[lib]
name = "AcRes"
crate-type = ["cdylib"]
